# Generated by Django 4.2 on 2023-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0002_remove_soldier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldierrelevant',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'هیچ'), (1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'زیاد'), (5, 'خیلی زیاد')], default=3, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=64, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='soldierrelevant',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='soldierrelevant',
            name='education_level',
            field=models.IntegerField(choices=[(0, 'ابتدایی'), (1, 'ششم متوسطه'), (2, 'هفتم متوسطه'), (3, 'هشتم متوسطه'), (4, 'نهم متوسطه'), (5, 'دهم متوسطه'), (6, 'یازدهم متوسطه'), (7, 'دوازدهم متوسطه')], verbose_name='سطح تحصیلات'),
        ),
        migrations.AlterField(
            model_name='soldierrelevant',
            name='job',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='soldierrelevant',
            name='relevance',
            field=models.CharField(choices=[('F', 'پدر'), ('M', 'مادر'), ('B', 'برادر'), ('S', 'خواهر'), ('W', 'همسر'), ('D', 'فرزند')], max_length=1, verbose_name='نسبت'),
        ),
    ]
