# Generated by Django 4.2 on 2023-05-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0003_soldierrelevant_name_alter_skill_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='soldierrelevant',
            options={'verbose_name': 'فرد نزدیک سرباز', 'verbose_name_plural': 'نزدیکان سرباز'},
        ),
    ]
