# Generated by Django 4.2 on 2023-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0004_alter_skill_options_alter_soldierrelevant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='being_poisoned_history',
            field=models.BooleanField(default=False, verbose_name='سابقه مسمومیت؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='currently_disease',
            field=models.BooleanField(default=False, verbose_name='آیا اکنون بیماری خاصی دارید؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='divorce_history',
            field=models.BooleanField(default=False, verbose_name='سابقه جدایی والدین؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='drug_consumption_history',
            field=models.BooleanField(default=False, verbose_name='سابقه سو مصرف مواد مخدر؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='family_drug_consumption_history',
            field=models.BooleanField(default=False, verbose_name='سابقه سو مصرف مواد در خانواده؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='family_psychological_problems_history',
            field=models.BooleanField(default=False, verbose_name='سابقه بیماری های روانی در خانواده؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='family_relation_with_each_other_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'هیچ'), (1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'زیاد'), (5, 'خیلی زیاد')], default=3, verbose_name='میزان روابط اعضای خانواده با یکدیگر؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='family_relation_with_parents_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'هیچ'), (1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'زیاد'), (5, 'خیلی زیاد')], default=3, verbose_name='میزان روابط با والدین؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='family_relation_with_siblings_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'هیچ'), (1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'زیاد'), (5, 'خیلی زیاد')], default=3, verbose_name='میزان روابط با خواهر  برادر؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='family_suicide_history',
            field=models.BooleanField(default=False, verbose_name='سابقه خودکشی در خانواده؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='former_disease',
            field=models.BooleanField(default=False, verbose_name='آیا سابقه بیماری خاصی داشته اید؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='head_accident_history',
            field=models.BooleanField(default=False, verbose_name='سابقه ضربه به سر و یا تصادف؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='hospitalization_history',
            field=models.BooleanField(default=False, verbose_name='سابقه بستری شدن؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='interviewer_opinions',
            field=models.TextField(default='', verbose_name='نظرات مصاحبه کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='medicine_treatment_history',
            field=models.BooleanField(default=False, verbose_name='سابقه درمان های دارویی اختلالات روانی؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='psycho_desease_history',
            field=models.BooleanField(default=False, verbose_name='سابقه اختلالات روانی؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='psychotrapy_consultant_history',
            field=models.BooleanField(default=False, verbose_name='سابقه مشاوره و روان درمانی؟'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='surgery_history',
            field=models.BooleanField(default=False, verbose_name='سابقه عمل جراحی؟'),
        ),
        migrations.AddField(
            model_name='soldierrelevant',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='آیا در قید حیات هستند؟'),
        ),
    ]
