# Generated by Django 4.2 on 2023-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0005_soldier_being_poisoned_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='interviewer_opinions',
            field=models.TextField(blank=True, null=True, verbose_name='نظرات مصاحبه کننده'),
        ),
    ]
